Repository kyma-project/modulectl, pull requests merged in 2024-11, with the labels that each got.

#96 chore: Remove git-remote flag
  cmd/modulectl/create/cmd_test.go
  cmd/modulectl/create/flags.go
  cmd/modulectl/create/flags_test.go
  docs/gen-docs/modulectl_create.md
  internal/service/create/create.go
  internal/service/create/create_test.go
  internal/service/create/options.go
  internal/service/create/options_test.go
  tests/e2e/create/create_suite_test.go
  tests/e2e/create/create_test.go
Labels: cla: yes, size/M, lgtm

#97 chore: Remove mis-imported dependencies github.com/mandelsoft/goutils
  go.mod
  go.sum
  internal/service/fileresolver/fileresolver_test.go
Labels: cla: yes, lgtm, size/S

#104 chore: Revert golangci-lint-action to `6.1.0`
  .github/workflows/lint-golangci.yml
Labels: cla: yes, size/XS

#114 fix: Add spec.ModuleName and spec.version to ModuleTemplate
  internal/service/templategenerator/templategenerator.go
  internal/service/templategenerator/templategenerator_test.go
  tests/e2e/create/create_test.go
Labels: cla: yes, size/M, lgtm

#115 feat: Migrate to checkmarxone
  sec-scanners-config.yaml
Labels: cla: yes, lgtm, size/XS

#112 feat: Error wrapping from newer to older in the error chain
  cmd/modulectl/create/cmd.go
  cmd/modulectl/scaffold/cmd.go
  internal/common/validation/validation.go
  internal/service/componentarchive/componentarchive.go
  internal/service/componentdescriptor/gitsources.go
  internal/service/componentdescriptor/securityconfig.go
  internal/service/contentprovider/moduleconfig.go
  internal/service/contentprovider/securityconfig.go
  internal/service/crdparser/crdparser.go
  internal/service/create/create.go
  internal/service/create/options.go
  internal/service/filegenerator/filegenerator.go
  internal/service/filegenerator/reusefilegenerator/reuse_filegenerator.go
  internal/service/filegenerator/reusefilegenerator/reuse_filegenerator_test.go
  internal/service/fileresolver/fileresolver.go
  internal/service/moduleconfig/generator/moduleconfig_generator.go
  internal/service/moduleconfig/reader/moduleconfig_reader.go
  internal/service/moduleconfig/reader/moduleconfig_reader_test.go
  internal/service/registry/registry.go
  internal/service/scaffold/errors.go
  internal/service/scaffold/options.go
  internal/service/scaffold/options_test.go
  internal/service/scaffold/scaffold.go
  internal/service/scaffold/scaffold_test.go
  internal/service/templategenerator/templategenerator.go
  tests/e2e/create/create_test.go
  tools/filesystem/archivefilesystem.go
  tools/filesystem/tempfilesystem.go
  tools/ocirepo/ocirepo.go
Labels: cla: yes, size/L
