Repository kyma-project/modulectl, pull requests merged in 2024-10, with the labels that each got.

#56 chore: Bump go version and setup action
  .github/dependabot.yml
  .github/workflows/build.yaml
  .github/workflows/lint-golangci.yml
  .github/workflows/test-e2e-create.yml
  .github/workflows/test-e2e-scaffold.yml
  .github/workflows/test-unit.yaml
  go.mod
Labels: cla: yes, lgtm, size/S

#64 deps: Import ocm.software instead of github.com/open-component-model
  .golangci.yaml
  go.mod
  go.sum
  internal/service/registry/registry.go
  tests/e2e/create/create_test.go
Labels: cla: yes, size/M, lgtm

#61 chore: Modulectl release
  .github/scripts/create_changelog.sh
  .github/scripts/draft_release.sh
  .github/scripts/get_release_by_tag.sh
  .github/scripts/publish_release.sh
  .github/scripts/upload_assets.sh
  .github/scripts/validate_release_tag.sh
  .github/workflows/build.yml
  .github/workflows/create-release.yml
  .github/workflows/test-unit.yml
  .github/workflows/validate-docs.yml
  Makefile
  cmd/main.go
  cmd/modulectl/cmd.go
  cmd/modulectl/version/cmd.go
  cmd/modulectl/version/cmd_test.go
  docs/gen-docs/modulectl.md
  docs/gen-docs/modulectl_version.md
  tests/e2e/create/create_test.go
Labels: cla: yes, lgtm, size/L

#67 fix: Release workflow
  .github/scripts/create_changelog.sh
  .github/scripts/draft_release.sh
  .github/scripts/get_release_by_tag.sh
  .github/scripts/publish_release.sh
  .github/scripts/upload_artifacts.sh
  .github/scripts/validate_release_tag.sh
  .github/workflows/create-release.yml
Labels: cla: yes, size/M, lgtm

#69 fix: Upload build artifacts for release
  .github/scripts/upload_artifacts.sh
  .github/workflows/create-release.yml
Labels: cla: yes, lgtm, size/S

#70 chore: Fix markdown used version
  .github/workflows/lint-markdown-links.yml
Labels: cla: yes, lgtm, size/XS

#71 feat: Shorten config flag
  cmd/modulectl/create/cmd_test.go
  cmd/modulectl/create/flags.go
  cmd/modulectl/create/flags_test.go
  cmd/modulectl/create/long.txt
  cmd/modulectl/create/use.txt
  docs/gen-docs/modulectl_create.md
  internal/service/create/create.go
  internal/service/create/create_test.go
  internal/service/create/options.go
  internal/service/create/options_test.go
  tests/e2e/create/create_suite_test.go
Labels: cla: yes, lgtm, size/L

#72 feat: Support adding Manager to moduletemplate
  .golangci.yaml
  go.mod
  go.sum
  internal/common/validation/validation.go
  internal/common/validation/validation_test.go
  internal/service/contentprovider/moduleconfig.go
  internal/service/moduleconfig/generator/moduleconfig_generator_test.go
  internal/service/moduleconfig/reader/moduleconfig_reader.go
  internal/service/moduleconfig/reader/moduleconfig_reader_test.go
  internal/service/templategenerator/templategenerator.go
  internal/service/templategenerator/templategenerator_test.go
  scaffold-create-config.yaml
  tests/e2e/create/create_suite_test.go
  tests/e2e/create/create_test.go
  tests/e2e/create/testdata/moduleconfig/valid/with-manager-no-namespace.yaml
  tests/e2e/create/testdata/moduleconfig/valid/with-manager.yaml
Labels: cla: yes, lgtm, size/XL

#76 chore: Bump ocm to 0.16.2 and remove the replace
  .golangci.yaml
  go.mod
  go.sum
Labels: cla: yes, size/M, lgtm

#73 feat: Generate `.spec.resources`
  cmd/modulectl/cmd.go
  internal/common/validation/validation.go
  internal/common/validation/validation_test.go
  internal/service/contentprovider/moduleconfig.go
  internal/service/contentprovider/moduleconfig_test.go
  internal/service/create/create.go
  internal/service/create/create_test.go
  internal/service/fileresolver/fileresolver.go
  internal/service/fileresolver/fileresolver_test.go
  internal/service/moduleconfig/generator/moduleconfig_generator_test.go
  internal/service/moduleconfig/reader/moduleconfig_reader.go
  internal/service/moduleconfig/reader/moduleconfig_reader_test.go
  internal/service/templategenerator/templategenerator.go
  internal/service/templategenerator/templategenerator_test.go
  tests/e2e/create/create_suite_test.go
  tests/e2e/create/create_test.go
  tests/e2e/create/testdata/moduleconfig/invalid/duplicate-resources.yaml
  tests/e2e/create/testdata/moduleconfig/invalid/empty-resource-name.yaml
  tests/e2e/create/testdata/moduleconfig/invalid/non-https-resource.yaml
  tests/e2e/create/testdata/moduleconfig/invalid/resource-without-link.yaml
  tests/e2e/create/testdata/moduleconfig/invalid/resource-without-name.yaml
  tests/e2e/create/testdata/moduleconfig/valid/with-resources-overwrite.yaml
  tests/e2e/create/testdata/moduleconfig/valid/with-resources.yaml
  unit-test-coverage.yaml
Labels: cla: yes, size/XXL

#78 docs: Rename to `--config-file` in remaining docs
  cmd/modulectl/create/example.txt
  docs/gen-docs/modulectl_create.md
  tests/e2e/create/create_test.go
Labels: cla: yes, lgtm, size/S

#81 chore: Remove local file support for `manifest` and `defaultCR`
  internal/common/validation/validation.go
  internal/service/fileresolver/fileresolver.go
  internal/service/fileresolver/fileresolver_test.go
  internal/service/moduleconfig/reader/moduleconfig_reader.go
  internal/service/moduleconfig/reader/moduleconfig_reader_test.go
  tests/e2e/create/create_suite_test.go
  tests/e2e/create/create_test.go
  tests/e2e/create/testdata/moduleconfig/invalid/defaultcr-fileref.yaml
  tests/e2e/create/testdata/moduleconfig/invalid/manifest-fileref.yaml
  unit-test-coverage.yaml
Labels: cla: yes, lgtm, size/L

#83 docs: Add new ModuleConfig fields documentation
  cmd/modulectl/create/long.txt
  docs/gen-docs/modulectl_create.md
Labels: cla: yes, size/M, lgtm

#82 fix: Update ModuleTemplate's Metadata name
  internal/service/templategenerator/templategenerator.go
  tests/e2e/create/create_test.go
Labels: cla: yes, lgtm, size/S

#87 chore: Remove ResourceName
  cmd/modulectl/create/long.txt
  docs/gen-docs/modulectl_create.md
  internal/service/contentprovider/moduleconfig.go
  internal/service/moduleconfig/generator/moduleconfig_generator_test.go
  internal/service/moduleconfig/reader/moduleconfig_reader_test.go
  internal/service/templategenerator/templategenerator.go
  internal/service/templategenerator/templategenerator_test.go
  scaffold-create-config.yaml
  tests/e2e/create/create_suite_test.go
  tests/e2e/create/create_test.go
  tests/e2e/create/testdata/moduleconfig/invalid/empty-resource-name.yaml
  tests/e2e/scaffold/scaffold_suite_test.go
Labels: cla: yes, lgtm, size/L

#89 chore: Remove Channel from ModuleConfig
  cmd/modulectl/create/long.txt
  cmd/modulectl/scaffold/cmd_test.go
  cmd/modulectl/scaffold/example.txt
  cmd/modulectl/scaffold/flags.go
  cmd/modulectl/scaffold/flags_test.go
  cmd/modulectl/scaffold/long.txt
  cmd/modulectl/scaffold/use.txt
  docs/gen-docs/modulectl_create.md
  docs/gen-docs/modulectl_scaffold.md
  go.mod
  go.sum
  internal/common/validation/validation.go
  internal/common/validation/validation_test.go
  internal/service/contentprovider/args.go
  internal/service/contentprovider/moduleconfig.go
  internal/service/contentprovider/moduleconfig_test.go
  internal/service/moduleconfig/generator/moduleconfig_generator_test.go
  internal/service/moduleconfig/reader/moduleconfig_reader.go
  internal/service/moduleconfig/reader/moduleconfig_reader_test.go
  internal/service/scaffold/options.go
  internal/service/scaffold/options_test.go
  internal/service/scaffold/scaffold.go
  internal/service/scaffold/scaffold_test.go
  internal/service/templategenerator/templategenerator.go
  internal/service/templategenerator/templategenerator_test.go
  scaffold-create-config.yaml
  tests/e2e/create/create_suite_test.go
  tests/e2e/create/create_test.go
  tests/e2e/create/testdata/moduleconfig/invalid/defaultcr-fileref.yaml
  tests/e2e/create/testdata/moduleconfig/invalid/duplicate-resources.yaml
  tests/e2e/create/testdata/moduleconfig/invalid/manifest-fileref.yaml
  tests/e2e/create/testdata/moduleconfig/invalid/missing-channel.yaml
  tests/e2e/create/testdata/moduleconfig/invalid/missing-manifest.yaml
  tests/e2e/create/testdata/moduleconfig/invalid/missing-name.yaml
  tests/e2e/create/testdata/moduleconfig/invalid/missing-version.yaml
  tests/e2e/create/testdata/moduleconfig/invalid/non-https-resource.yaml
  tests/e2e/create/testdata/moduleconfig/invalid/resource-without-link.yaml
  tests/e2e/create/testdata/moduleconfig/invalid/resource-without-name.yaml
  tests/e2e/create/testdata/moduleconfig/valid/minimal.yaml
  tests/e2e/create/testdata/moduleconfig/valid/with-annotations.yaml
  tests/e2e/create/testdata/moduleconfig/valid/with-associated-resources.yaml
  tests/e2e/create/testdata/moduleconfig/valid/with-defaultcr.yaml
  tests/e2e/create/testdata/moduleconfig/valid/with-manager-no-namespace.yaml
  tests/e2e/create/testdata/moduleconfig/valid/with-manager.yaml
  tests/e2e/create/testdata/moduleconfig/valid/with-mandatory.yaml
  tests/e2e/create/testdata/moduleconfig/valid/with-resources-overwrite.yaml
  tests/e2e/create/testdata/moduleconfig/valid/with-resources.yaml
  tests/e2e/create/testdata/moduleconfig/valid/with-security.yaml
  tests/e2e/scaffold/scaffold_suite_test.go
  tests/e2e/scaffold/scaffold_test.go
  unit-test-coverage.yaml
Labels: cla: yes, lgtm, size/L
