Repository kyma-project/modulectl, pull requests merged in 2024-08, with the labels that each got.

#38 chore(deps): Bump go and docker package versions
  go.mod
  go.sum
Labels: cla: yes, lgtm, size/L

#41 chore: Add lint pipeline
  .github/workflows/lint-golangci.yml
  .golangci.yaml
  Makefile
  cmd/modulectl/cmd.go
  cmd/modulectl/create/cmd.go
  cmd/modulectl/create/scaffold/cmd.go
  cmd/modulectl/create/scaffold/cmd_test.go
  cmd/modulectl/create/scaffold/flags.go
  cmd/modulectl/create/scaffold/flags_test.go
  docs/gen-docs/modulectl.md
  docs/gen-docs/modulectl_create.md
  internal/service/contentprovider/defaultcr_test.go
  internal/service/contentprovider/manifest_test.go
  internal/service/contentprovider/moduleconfig.go
  internal/service/contentprovider/moduleconfig_test.go
  internal/service/contentprovider/securityconfig.go
  internal/service/contentprovider/securityconfig_test.go
  internal/service/filegenerator/filegenerator.go
  internal/service/filegenerator/filegenerator_test.go
  internal/service/filegenerator/reusefilegenerator/errors.go
  internal/service/filegenerator/reusefilegenerator/reuse_filegenerator.go
  internal/service/filegenerator/reusefilegenerator/reuse_filegenerator_test.go
  internal/service/moduleconfig/errors.go
  internal/service/moduleconfig/moduleconfig.go
  internal/service/moduleconfig/moduleconfig_test.go
  internal/service/scaffold/errors.go
  internal/service/scaffold/options.go
  internal/service/scaffold/scaffold.go
  internal/service/scaffold/scaffold_test.go
  scripts/gendocs/gendocs.go
  tests/e2e/create/scaffold/scaffold_test.go
  tools/filesystem/filesystem.go
  tools/io/out.go
  tools/yaml/yaml.go
Labels: cla: yes, lgtm, size/XL

#43 fix: Adjust ModuleConfig File Format
  internal/service/contentprovider/moduleconfig.go
  tests/e2e/create/scaffold/scaffold_test.go
Labels: cla: yes, size/M, lgtm
