Repository kyma-project/modulectl, pull requests merged in 2024-12, with the labels that each got.

#116 feat: Introduce mandatory module Label in module create
  internal/service/templategenerator/templategenerator.go
  internal/service/templategenerator/templategenerator_test.go
  tests/e2e/create/create_test.go
Labels: cla: yes, size/M, lgtm

#118 chore: Remove Beta and Internal flags with its related dependencies
  cmd/modulectl/create/long.txt
  docs/gen-docs/modulectl_create.md
  internal/service/contentprovider/moduleconfig.go
  internal/service/moduleconfig/generator/moduleconfig_generator_test.go
  internal/service/moduleconfig/reader/moduleconfig_reader_test.go
  internal/service/templategenerator/templategenerator.go
  tests/e2e/scaffold/scaffold_suite_test.go
Labels: cla: yes, lgtm, size/S

#127 docs: Migrating from Kyma CLI to modulectl
  docs/contributor/migration-guide.md
Labels: cla: yes, size/M, lgtm

#128 docs: Add mandatory modules documentation to the migration-guide.md
  docs/contributor/migration-guide.md
Labels: cla: yes, lgtm, size/XS

#132 feat(Maintenance Windows): Add requires downtime to moduleconfig
  cmd/modulectl/create/long.txt
  docs/gen-docs/modulectl_create.md
  go.mod
  go.sum
  internal/service/contentprovider/moduleconfig.go
  internal/service/moduleconfig/generator/moduleconfig_generator_test.go
  internal/service/moduleconfig/reader/moduleconfig_reader_test.go
  internal/service/templategenerator/templategenerator.go
  internal/service/templategenerator/templategenerator_test.go
  tests/e2e/create/create_suite_test.go
  tests/e2e/create/create_test.go
  tests/e2e/create/testdata/moduleconfig/valid/with-requiresDowntime.yaml
Labels: cla: yes, lgtm, size/L
