Repository kyma-project/modulectl, pull requests merged in 2025-02, with the labels that each got.

#151 feat: Add grouping to `dependabot` PRs
  .github/dependabot.yml
Labels: cla: yes, size/S

#158 chore: Bump go version to 1.23.6
  go.mod
Labels: cla: yes, lgtm, size/XS

#163 fix: Allow `latest` Tag in Protecode of `sec-scanners-config.yaml`
  internal/service/componentdescriptor/securityconfig.go
  internal/service/componentdescriptor/securityconfig_test.go
  internal/service/contentprovider/securityconfig.go
  internal/service/contentprovider/securityconfig_test.go
  internal/service/create/create.go
  internal/utils/image.go
  internal/utils/image_test.go
  unit-test-coverage.yaml
Labels: cla: yes, size/L

#168 feat: Support overwrite flag for the pushed component version
  cmd/modulectl/create/flags.go
  docs/gen-docs/modulectl_create.md
  internal/service/create/create.go
  internal/service/create/create_test.go
  internal/service/create/options.go
  internal/service/registry/registry.go
  internal/service/registry/registry_test.go
  tests/e2e/create/create_suite_test.go
  tests/e2e/create/create_test.go
  tools/ocirepo/ocirepo.go
Labels: cla: yes, lgtm, size/L

#171 docs: Align docs for ModuleConfig type and Create command help
  cmd/modulectl/create/long.txt
  docs/gen-docs/modulectl_create.md
  internal/service/contentprovider/moduleconfig.go
Labels: cla: yes, lgtm, size/L

#173 feat: Introduce `--dry-run` flag
  cmd/modulectl/create/flags.go
  cmd/modulectl/create/flags_test.go
  docs/gen-docs/modulectl_create.md
  internal/service/create/create.go
  internal/service/create/options.go
  internal/service/create/options_test.go
  internal/service/templategenerator/templategenerator.go
  internal/service/templategenerator/templategenerator_test.go
  tests/e2e/create/create_suite_test.go
  tests/e2e/create/create_test.go
  unit-test-coverage.yaml
Labels: cla: yes, lgtm, size/L

#177 fix: Create test e2e files not asserted correctly
  tests/e2e/create/create_test.go
Labels: cla: yes, size/XS

#179 fix: Create test cleanup
  tests/e2e/create/create_test.go
Labels: cla: yes, lgtm, size/XL

#180 chore: Provide local test scripts and description
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  docs/contributor/local-test-setup.md
  scripts/build-modulectl.sh
  scripts/delete-test-registry.sh
  scripts/re-create-test-registry.sh
  scripts/run-e2e-test.sh
Labels: cla: yes, lgtm, size/L
