Repository kyma-project/modulectl, pull requests merged in 2025-03, with the labels that each got.

#182 chore: Limit GH workflow permissions
  .github/workflows/build.yml
  .github/workflows/create-release.yml
  .github/workflows/lint-conventional-prs.yml
  .github/workflows/lint-golangci.yml
  .github/workflows/lint-markdown-links.yml
  .github/workflows/stale.yml
  .github/workflows/test-e2e-create.yml
  .github/workflows/test-e2e-scaffold.yml
  .github/workflows/test-unit-coverage.yml
  .github/workflows/test-unit.yml
  .github/workflows/validate-docs.yml
Labels: cla: yes, size/M, lgtm

#183 chore: Update security scanners config for checkmarxone migration
  sec-scanners-config.yaml
Labels: cla: yes, size/S

#184 chore: Rename 'protecode' to 'bdba'
  internal/service/componentdescriptor/securityconfig.go
  internal/service/componentdescriptor/securityconfig_test.go
  internal/service/contentprovider/securityconfig.go
  internal/service/contentprovider/securityconfig_test.go
  tests/e2e/create/testdata/sec-scanners-config/config.yaml
Labels: size/M, lgtm

#185 chore: Add "contents: write" Permission to Create Release Workflow
  .github/workflows/create-release.yml
Labels: lgtm, size/XS

#189 docs: Add Documentation for Repository Landing Page
  README.md
Labels: size/M, lgtm

#161 chore: Remove docker in dependabot
  .github/dependabot.yml
Labels: cla: yes, lgtm, size/S
